[build]
  command = "npm run build"  # Run the build script specified in your package.json
  functions = "netlify/functions"
  publish = "dist"  # The directory where your built files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
